services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=Admin
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_DB=postgres #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 5005:8080